"""Initial schema with enhanced question types

Revision ID: d464c704f3d6
Revises: 
Create Date: 2025-08-21 08:05:03.994287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd464c704f3d6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('channel_users_channel_id_user_id_key'), 'channel_users', type_='unique')
    op.create_index('uq_channel_users', 'channel_users', ['channel_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_channel_users', table_name='channel_users')
    op.create_unique_constraint(op.f('channel_users_channel_id_user_id_key'), 'channel_users', ['channel_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
